name = "hello_world"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-16"

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "./build.sh" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
